/* tslint:disable */
/* eslint-disable */
/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AccountBalanceRequest,
    AccountBalanceRequestToJSON,
    AccountBalanceResponse,
    AccountBalanceResponseFromJSON,
    AccountCoinsRequest,
    AccountCoinsRequestToJSON,
    AccountCoinsResponse,
    AccountCoinsResponseFromJSON,
} from '../models';
import * as runtime from '../runtime';

export interface AccountBalanceOperationRequest {
    accountBalanceRequest: AccountBalanceRequest;
}

export interface AccountCoinsOperationRequest {
    accountCoinsRequest: AccountCoinsRequest;
}

/**
 *
 */
export class AccountApi extends runtime.BaseAPI {
    /**
     * Get an array of all AccountBalances for an AccountIdentifier and the BlockIdentifier at which the balance lookup was performed. The BlockIdentifier must always be returned because some consumers of account balance data need to know specifically at which block the balance was calculated to compare balances they compute from operations with the balance returned by the node. It is important to note that making a balance request for an account without populating the SubAccountIdentifier should not result in the balance of all possible SubAccountIdentifiers being returned. Rather, it should result in the balance pertaining to no SubAccountIdentifiers being returned (sometimes called the liquid balance). To get all balances associated with an account, it may be necessary to perform multiple balance requests with unique AccountIdentifiers. It is also possible to perform a historical balance lookup (if the server supports it) by passing in an optional BlockIdentifier.
     * Get an Account\'s Balance
     */
    async accountBalanceRaw(
        requestParameters: AccountBalanceOperationRequest,
        initOverrides?: RequestInit,
    ): Promise<runtime.ApiResponse<AccountBalanceResponse>> {
        if (requestParameters.accountBalanceRequest === null || requestParameters.accountBalanceRequest === undefined) {
            throw new runtime.RequiredError(
                'accountBalanceRequest',
                'Required parameter requestParameters.accountBalanceRequest was null or undefined when calling accountBalance.',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request(
            {
                path: `/account/balance`,
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
                body: AccountBalanceRequestToJSON(requestParameters.accountBalanceRequest),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountBalanceResponseFromJSON(jsonValue));
    }

    /**
     * Get an array of all AccountBalances for an AccountIdentifier and the BlockIdentifier at which the balance lookup was performed. The BlockIdentifier must always be returned because some consumers of account balance data need to know specifically at which block the balance was calculated to compare balances they compute from operations with the balance returned by the node. It is important to note that making a balance request for an account without populating the SubAccountIdentifier should not result in the balance of all possible SubAccountIdentifiers being returned. Rather, it should result in the balance pertaining to no SubAccountIdentifiers being returned (sometimes called the liquid balance). To get all balances associated with an account, it may be necessary to perform multiple balance requests with unique AccountIdentifiers. It is also possible to perform a historical balance lookup (if the server supports it) by passing in an optional BlockIdentifier.
     * Get an Account\'s Balance
     */
    async accountBalance(accountBalanceRequest: AccountBalanceRequest, initOverrides?: RequestInit): Promise<AccountBalanceResponse> {
        const response = await this.accountBalanceRaw({ accountBalanceRequest: accountBalanceRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Get an array of all unspent coins for an AccountIdentifier and the BlockIdentifier at which the lookup was performed. If your implementation does not support coins (i.e. it is for an account-based blockchain), you do not need to implement this endpoint. If you implementation does support coins (i.e. it is fro a UTXO-based blockchain), you MUST also complete the `/account/balance` endpoint. It is important to note that making a coins request for an account without populating the SubAccountIdentifier should not result in the coins of all possible SubAccountIdentifiers being returned. Rather, it should result in the coins pertaining to no SubAccountIdentifiers being returned. To get all coins associated with an account, it may be necessary to perform multiple coin requests with unique AccountIdentifiers. Optionally, an implementation may choose to support updating an AccountIdentifier\'s unspent coins based on the contents of the mempool. Note, using this functionality breaks any guarantee of idempotency.
     * Get an Account\'s Unspent Coins
     */
    async accountCoinsRaw(
        requestParameters: AccountCoinsOperationRequest,
        initOverrides?: RequestInit,
    ): Promise<runtime.ApiResponse<AccountCoinsResponse>> {
        if (requestParameters.accountCoinsRequest === null || requestParameters.accountCoinsRequest === undefined) {
            throw new runtime.RequiredError(
                'accountCoinsRequest',
                'Required parameter requestParameters.accountCoinsRequest was null or undefined when calling accountCoins.',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request(
            {
                path: `/account/coins`,
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
                body: AccountCoinsRequestToJSON(requestParameters.accountCoinsRequest),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountCoinsResponseFromJSON(jsonValue));
    }

    /**
     * Get an array of all unspent coins for an AccountIdentifier and the BlockIdentifier at which the lookup was performed. If your implementation does not support coins (i.e. it is for an account-based blockchain), you do not need to implement this endpoint. If you implementation does support coins (i.e. it is fro a UTXO-based blockchain), you MUST also complete the `/account/balance` endpoint. It is important to note that making a coins request for an account without populating the SubAccountIdentifier should not result in the coins of all possible SubAccountIdentifiers being returned. Rather, it should result in the coins pertaining to no SubAccountIdentifiers being returned. To get all coins associated with an account, it may be necessary to perform multiple coin requests with unique AccountIdentifiers. Optionally, an implementation may choose to support updating an AccountIdentifier\'s unspent coins based on the contents of the mempool. Note, using this functionality breaks any guarantee of idempotency.
     * Get an Account\'s Unspent Coins
     */
    async accountCoins(accountCoinsRequest: AccountCoinsRequest, initOverrides?: RequestInit): Promise<AccountCoinsResponse> {
        const response = await this.accountCoinsRaw({ accountCoinsRequest: accountCoinsRequest }, initOverrides);
        return await response.value();
    }
}
