/* tslint:disable */
/* eslint-disable */
/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Case specifies the expected case for strings and hashes.
 * @export
 * @enum {string}
 */
export enum Case {
    upper_case = 'upper_case',
    lower_case = 'lower_case',
    case_sensitive = 'case_sensitive',
    null = 'null',
}

export function CaseFromJSON(json: any): Case {
    return CaseFromJSONTyped(json, false);
}

export function CaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Case {
    return json as Case;
}

export function CaseToJSON(value?: Case | null): any {
    return value as any;
}
