name: Build
on: [push]
jobs:
    build:
        name: Build, Test, Coverage
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: https://registry.npmjs.org
            - run: npm ci
            - run: npm pack
            - run: npm test
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 18.x
                  registry-url: https://registry.npmjs.org
            - run: npm ci
            - run: npm run lint
