name: Github Pages
on:
    push:
        branches: [main]
jobs:
    doc:
        name: Github Pages Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 18.x
                  registry-url: https://registry.npmjs.org
            - run: npm ci
            - run: npm run doc
            - name: Deploy Docs
              uses: JamesIves/github-pages-deploy-action@v4.2.2
              with:
                  branch: gh-pages
                  folder: ts-docs
